name: Fetch latest news
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug tree
        run: |
          pwd
          ls -la
          echo "---- scripts ----"
          ls -la scripts || true
          echo "---- data ----"
          ls -la data || true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build latest.json
        run: node scripts/build_latest.js

      - name: Commit & push latest.json
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git add data/latest.json
          git commit -m "update latest.json" || echo "No changes"
          git push
